### ISSUE TITLE
v1.2.19 broke posthog.Capture

### ISSUE THREAD

**Issue by migueldv90** [PostHog/posthog-go#69]
I am currently integrating Posthog in a go environment. It seems that from version v1.2.18 to v1.2.19 posthog.Capture broke. I was able to use posthog.Identify without problem but was not able to use posthog.Capture. I had to downgrade to v1.2.18 and everything seems to work as expected.

The error I am getting is -
posthog 2024/08/24 23:59:13 INFO: response 400 400 Bad Request – failed to parse request: data did not match any variant of untagged enum RawRequest

I was not able to pinpoint the specific problem. But I think it has to do with "Ability to specify uuid when capturing events" #68

**Comment by tylergannon** [comment]
Yeah we auto-updated to 1.2.19 and it took down our event monitoring.  Had to roll back to 1.2.18.

**Comment by migueldv90** [comment]
It looks like they have fixed it. I will confirm later and will close this issue when I can verify.

**Comment by dmarticus** [comment]
@migueldv90 can you confirm that this has been fixed for you?  Just doing some housekeeping on our issues and I think this has been resolved, but wanted to double-check.

**Comment by dmarticus** [comment]
Closing since I tested this myself, but feel free to reopen if I'm wrong

**Comment by migueldv90** [comment]
@dmarticus 
Yes, this is working.

Thank you!
